### ISSUE TITLE
Missing `sharedKey` when following documentation

### ISSUE THREAD

**Issue by ryanleh** [mc2-project/opaque#205]
In Step 3 of the `Running the interactive shell` section of `Using Opaque SQL` I get the following error when running `edu.berkeley.cs.rise.opaque.Utils.initSQLContext(spark.sqlContext)`:
```
edu.berkeley.cs.rise.opaque.OpaqueException: Cannot begin attestation without sharedKey.
  at edu.berkeley.cs.rise.opaque.RA$.initRA(RA.scala:47)
  at edu.berkeley.cs.rise.opaque.RA$.attestEnclaves(RA.scala:110)
  at edu.berkeley.cs.rise.opaque.Utils$.initSQLContext(Utils.scala:316)
  ... 49 elided
```

This can be fixed by starting the shell with
```
spark-shell --jars ${OPAQUE_HOME}/target/scala-2.12/opaque_2.12-0.1.jar --conf spark.opaque.testing.enableSharedKey=true
```

instead of what's specified in the docs:
```
spark-shell --jars ${OPAQUE_HOME}/target/scala-2.12/opaque_2.12-0.1.jar
```

But I'm assuming that you don't want to include that configuration flag in this section since it shouldn't be used in production. Perhaps you could specify it's necessary for local testing or something? Or am I doing something wrong?

**Comment by octaviansima** [comment]
I think we need stronger documentation to make it explicitly clear that running anything that isn't the Listener class requires a trusted driver in which this flag is enabled (even Listener currently requires this, however). Basically, nothing but `spark-submit --class edu.berkeley.cs.rise.opaque.rpc.Listener ...` should be used in production in the future. @wzheng what do you think?

**Comment by wzheng** [comment]
Yes, we should specify that we only work in the single party setting, and that the driver program must be put on the client side for production usage, and the testing key should not be used. For anything other than production, the testing key can be enabled. We should document this configuration [here](https://mc2-project.github.io/opaque/usage/usage.html). I wonder if we want to also have a specific section on "Deploying in production"? Though we used to say that Opaque is experimental.

**Comment by octaviansima** [comment]
I like the "deploying in production" idea. I think we should also mention that attestation or log verification is not currently supported in there as well.

**Comment by octaviansima** [comment]
@ryanleh when you have time, can you please work on these amendments to the docs? You've been very thorough with finding gaps in them so far.
